### ISSUE TITLE
Crash when open PanelSDK

### ISSUE THREAD

**Issue by lordnegre** [TuyaInc/tuyasmart_panel_ios_sdk#3]
You are using UIAlertView instead UIalertController inside the sdk. UIAlertView is deprecated from iOS13+ so your sdk is unusable. Could you fix it?

`Terminating app due to uncaught exception 'NSObjectNotAvailableException', reason: 'UIAlertView is deprecated and unavailable for UIScene based applications, please use UIAlertController!'
*** First throw call stack:
(0x187eb0300 0x187bc4c1c 0x187d9fe68 0x18b5a2188 0x18b5a26e8 0x10286ec28 0x1028e8630 0x1028e7a34 0x102c7da8c 0x1027a5c74 0x10279f8d8 0x1027a9568 0x1027a95dc 0x102c2ec6c 0x103b69d10 0x103b6b18c 0x103b79d14 0x187e2b6b0 0x187e262c8 0x187e258f4 0x19223c604 0x18bff9358 0x1027a3824 0x187ca12dc)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by misakatao** [comment]
UIScene base application that is new yet not support UIAlertView so it crashes the app, you can remove the UIScene base application, you can use window base application.

**Comment by lordnegre** [comment]
Without UIScene all applications launched on iOS 13+ devices will have a black screen because is mandatory in iOS 13+ and Xcode 11. Moreover, starting June 30, Apple won't accept applications submitted with older versions than Xcode 11.

https://developer.apple.com/news/?id=03262020b

That change is mandatory to use your SDK

**Comment by misakatao** [comment]
iPhone applications may not need to use UIScene.

**Comment by lordnegre** [comment]
So, does your SDK support iPad OS? Can we develop universal apps (iPhone/iPad) with multi screen scene support?

**Comment by misakatao** [comment]
In a future we will support iPad OS and  multi screen scene.

**Comment by lordnegre** [comment]
Thanks for your reply, could you please update this issue when that feature is ready?

**Comment by misakatao** [comment]
Sure, thanks for your feedback.
